# Copyright (c) 2017 Wind River Systems Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.4'
services:
  layerindex:
    hostname: layerindex
    image: windriver/layerindex
    # ports:
    #   - '5000:5000'
    environment:
      LAYERINDEX_ADMIN: "admin"
      LAYERINDEX_ADMIN_EMAIL: "admin@localhost"
      LAYERINDEX_ADMIN_PASS: "admin"
      GUNICORN_NUM_WORKERS: '1'
      GUNICORN_BIND: '0.0.0.0:5000'
      CELERY_NUM_WORKERS: 1
      STARTUP_DELAY: 5
      SECRET_KEY: "${SECRET_KEY:-1234}"
    depends_on:
      - mariadb
      - rabbit
    links:
      - rabbit
      - mariadb
    tmpfs:
      - /tmp:exec
    volumes:
      - /opt/layers

  mariadb:
    image: mariadb
    # Enable UTF-8 for tables
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'layerindex'
      MYSQL_USER: 'oelayer'
      MYSQL_PASSWORD: 'oelayer'
      LANG: 'en_US.UTF-8'
    tmpfs:
      - /tmp:exec
    healthcheck:
      test: ["CMD", "mysql", '--user=oelayer', '--password=oelayer', "-e", "show databases;"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 2m

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
