- branch: master
  build:
  - bitbake
  - core-image-minimal
  name: master-minimal
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=oecore_sstate
  - --enable-bootimage=ext4
  setup:
  - wr-lx-setup.sh
  - --machine=qemux86-64
  - --distro=poky
  - --layers=meta-poky
