- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: intel-x86-64_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=intel-x86-64
  - --dl-layers
  - --templates=feature/target-toolchain

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: intel-x86-32_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=intel-x86-32
  - --dl-layers
  - --templates=feature/target-toolchain

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: intel-corei7-64_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --kernel-type=linux-yocto-rt
  - --target-supported-ktype=preempt-rt
  - --enable-bootimage=hddimg
  - --whitelist-intel-package='linux-intel,linux-intel-rt,thermald'
  - --enable-shared-sstate=wrl1020_sstate_cache
  - --no-network=0
  setup:
  - --machine=intel-corei7-64
  - --dl-layers
  - --templates=feature/target-toolchain

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: intel-core2-32_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --kernel-type=linux-yocto-rt
  - --target-supported-ktype=preempt-rt
  - --whitelist-intel-package='linux-intel,linux-intel-rt,thermald,gma500-gfx-check'
  - --enable-shared-sstate=wrl1020_sstate_cache
  - --no-network=0
  - --enable-bootimage=ext4
  setup:
  - --machine=intel-core2-32
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: genericx86_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --kernel-type=linux-yocto-dev
  - --enable-bootimage=hddimg
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --machine=genericx86
  - --dl-layers
  - --templates=feature/target-toolchain

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: genericx86-64_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --kernel-type=linux-yocto-dev
  - --enable-bootimage=hddimg
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --machine=genericx86-64
  - --dl-layers
  - --templates=feature/target-toolchain

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: intel-haswell-64_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --machine=intel-haswell-64
  - --dl-layers
  - --templates=feature/target-toolchain

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: intel-skylake-64_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=intel-skylake-64
  - --dl-layers
  - --templates=feature/target-toolchain

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: intel-skylake-avx512-32_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=intel-skylake-avx512-32
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: intel-skylake-avx512-64_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=intel-skylake-avx512-64
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: nxp-imx7_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=nxp-imx7
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-glibc-std'
  name: nxp-ls20xx_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=nxp-ls20xx
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: nxp-ls10xx_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=nxp-ls10xx
  - --dl-layers
  - --templates=feature/target-toolchain

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: xilinx-zynqmp_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=xilinx-zynqmp
  - --dl-layers

- branch: master-wr
  build:
  - 'git clone git://ala-lxgit.wrs.com/wrlinux-testing/testcases.git;'
  - 'bitbake-layers add-layer testcases/wr-testing/kts-dev;'
  - 'echo "WRTEMPLATE_append = \" feature/ltp feature/test feature/gdb feature/linux-yocto-dev\"" >> conf/local.conf;'
  - 'bitbake wrlinux-image-std'
  name: intel-x86-64_ltp_wrlinux-image-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=intel-x86-64
  - --dl-layers

- branch: master-wr
  build:
  - 'git clone git://ala-lxgit.wrs.com/wrlinux-testing/testcases.git;'
  - 'bitbake-layers add-layer testcases/wr-testing/kts-dev;'
  - 'echo "WRTEMPLATE_append = \" feature/ltp feature/test feature/gdb feature/linux-yocto-dev\"" >> conf/local.conf;'
  - 'bitbake wrlinux-image-std'
  name: xilinx-zynqmp_ltp_wrlinux-image-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=xilinx-zynqmp
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: qemuarma9_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=qemuarma9
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: qemuarm64_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=qemuarm64
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: qemuarm_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=qemuarm
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: qemuarmv5_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=qemuarmv5
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: qemux86_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=qemux86
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: qemux86-64_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=qemux86-64
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std-sato'
  name: qemux86-64_wrlinux-graphics-image-glibc-std-sato
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux-graphics
  - --machine=qemux86-64
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std-sato'
  name: qemux86_wrlinux-graphics-image-glibc-std-sato
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux-graphics
  - --machine=qemux86
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std-sato'
  name: qemuarm_wrlinux-graphics-image-glibc-std-sato
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux-graphics
  - --machine=qemuarm
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std-sato'
  name: qemuarm64_wrlinux-graphics-image-glibc-std-sato
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux-graphics
  - --machine=qemuarm64
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std-sato'
  name: qemuppc_wrlinux-graphics-image-glibc-std-sato
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux-graphics
  - --machine=qemuppc
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std-sato'
  name: qemumips64_wrlinux-graphics-image-glibc-std-sato
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux-graphics
  - --machine=qemumips64
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-glibc-cgl'
  name: qemux86-64_wrlinux-image-glibc-cgl
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  - --no-network=0
  setup:
  - --distro=wrlinux-cgl
  - --machine=qemux86-64
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: qemuppc_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=qemuppc
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: qemumips64_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=qemumips64
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: qemumips_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=qemumips
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: mpc8315e-rdb_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=mpc8315e-rdb
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: beaglebone-yocto_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=beaglebone-yocto
  - --dl-layers
  - --templates=feature/target-toolchain

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: edgerouter_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=edgerouter
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: ti-am335x_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=ti-am335x
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-glibc-std'
  name: marvell-cn96xx_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=marvell-cn96xx
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-glibc-std'
  name: xilinx-zynq_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=xilinx-zynq
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-glibc-std'
  name: renesas-rcar-m3_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  - --enable-bootimage=ext4
  setup:
  setup:
  - --distro=wrlinux
  - --machine=renesas-rcar-m3
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-glibc-std'
  name: renesas-rcar-h3_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=renesas-rcar-h3
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: bcm-2xxx-rpi4_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  - --enable-bootimage=ext4
  setup:
  setup:
  - --distro=wrlinux
  - --machine=bcm-2xxx-rpi4
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: qemuriscv64_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-bootimage=ext4
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --machine=qemuriscv64
  - --dl-layers

- branch: master-wr
  build:
  - 'bitbake wrlinux-image-std'
  name: ti-am65x_wrlinux-image-glibc-std
  prebuild:
  - build_configure.sh
  - --enable-shared-sstate=wrl1020_sstate_cache
  setup:
  - --distro=wrlinux
  - --machine=ti-am65x
  - --dl-layers

